#! /bin/sh

# Place this file in /etc. Will be called by dhclient when it receives
# new information.

if [ -f /etc/radns-resolv.conf ]
then
  cp /etc/radns-resolv.conf /etc/resolv.conf

  if [ -n "$new_domain_name_servers" ]
  then
    for nameserver in $new_domain_name_servers
    do
      echo "nameserver $nameserver" >>/etc/resolv.conf
    done
  fi
fi
