#! /bin/sh

# Place this file in /etc. Will be called by dhclient when it receives
# new information.

if [ -f /etc/radns-resolv.conf ]
then
  > /etc/resolv.conf
  [ "$new_domain_search" ] && echo search $new_domain_search >> /etc/resolv.conf
  [ "$new_domain_name" ] && echo domain $new_domain_name >> /etc/resolv.conf
  cat /etc/radns-resolv.conf >> /etc/resolv.conf

  if [ -n "$new_domain_name_servers" ]
  then
    for nameserver in $new_domain_name_servers
    do
      echo "nameserver $nameserver" >>/etc/resolv.conf
    done
  fi
fi
