#! /bin/sh
# -*- shell-script -*-

PATH=$PATH:/usr/local/sbin
export PATH

echo ----------------- radns-script -----------------

echo interface: $if
echo resolv_conf: $resolv_conf


if [ "$if" = "" ]
then
    exit 1;
fi

if [ "$resolv_conf" = "" ]
then
    if [ $verbose -gt 0 ]
    then
        echo "$0: Environment variable $resolv_conf not set. Exiting..."
    fi
    exit 1
fi

# Do nothing if $resolv_conf is not an ordinary file
if [ ! -f $resolv_conf ]
then
    if [ $verbose -gt 0 ]
    then
        echo "$0: $resolv_conf is not an ordinary file or does not exist. Exiting..."
    fi
    exit 1
fi

# resolvconf's interface directory
# (/usr/local/etc/resolvconf/run/interfaces/ on FreeBSD) needs to be
# writable by our user, by default 'radns'.

resolvconf -a $if < $resolv_conf

echo +++++++++++++++++ radns+script +++++++++++++++++
